DROP TABLE IF EXISTS PETSALE;

CREATE TABLE PETSALE (
	ID INTEGER NOT NULL,
	ANIMAL VARCHAR(20),
	SALEPRICE DECIMAL(6,2),
	SALEDATE DATE,
	QUANTITY INTEGER,
	PRIMARY KEY (ID)
	);

INSERT INTO PETSALE VALUES
(1,'Cat',450.09,'2018-05-29',9),
(2,'Dog',666.66,'2018-06-01',3),
(3,'Parrot',50.00,'2018-06-04',2),
(4,'Hamster',60.60,'2018-06-11',6),
(5,'Goldfish',48.48,'2018-06-14',24);

SELECT * FROM PETSALE;

CREATE PROCEDURE RETRIEVE_ALL
AS 
BEGIN
	SELECT * FROM PETSALE;
END;
EXEC RETRIEVE_ALL;

--You will create a stored procedure routine named UPDATE_SALEPRICE with parameters Animal_ID and Animal_Health, Animal_Health='BAD', discount =25%, Animal_Health='WORSE', discount =50%
CREATE PROCEDURE UPDATE_SALEPRICE(
@Animal_ID AS INTEGER, @Animal_Health AS VARCHAR(5)
)
AS
BEGIN
	IF @Animal_Health = 'BAD'  
	BEGIN 
		UPDATE PETSALE
		SET SALEPRICE = SALEPRICE - (SALEPRICE*0.25)
		WHERE ID = @Animal_ID;
	END
	ELSE IF @Animal_Health = 'WORSE'  
	BEGIN
		UPDATE PETSALE
		SET SALEPRICE = SALEPRICE - (SALEPRICE*0.25)
		WHERE ID = @Animal_ID;
	END
	ELSE 
	BEGIN
		UPDATE PETSALE
        SET SALEPRICE = SALEPRICE
        WHERE ID = @Animal_ID;
	END
END;
EXEC RETRIEVE_ALL;
EXEC UPDATE_SALEPRICE 1, 'BAD';